"""
Django settings for tazboard project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os

# secret key can be specefied with env var
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

TEST_RUNNER = 'tazboard.api.tests.runner.NoDbTestRunner'

INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'rest_framework',
    'tazboard.frontend',
    'tazboard.api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'tazboard.core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [],
        },
    },
]

WSGI_APPLICATION = 'tazboard.core.wsgi.application'
DATABASES = {}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

REST_FRAMEWORK = {
    'UNAUTHENTICATED_USER': None,
    'DEFAULT_PERMISSION_CLASSES': [],
    'DEFAULT_AUTHENTICATION_CLASSES': []
}

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'
USE_I18N = False
USE_L10N = False
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = 'static'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# taz specific configuration

TAZBOARD_ELASTIC_HOST = 'datalake.taz.de'
TAZBOARD_ELASTIC_PORT = 9201
TAZBOARD_ELASTIC_SSL = True
TAZBOARD_ELASTIC_VERIFY_CERT = False

# only query the relevant indices and ignore everything else in the ES
TAZBOARD_ELASTIC_INDEX = 'article-*'

# Only for testing!
TAZBOARD_MOCKS_ENABLED = False

TAZBOARD_NUMBER_FIREPLACE_POSITIONS = 10
TAZBOARD_ID_FIREPLACE_CXML = 4608
TAZBOARD_CXML_HOST = 'taz.de'
TAZBOARD_CXML_ARTICLE_HOST = 'static.taz.de'
TAZBOARD_CXML_XFORWARD_HEADER = 'downey.taz.de'
TAZBOARD_CXML_USER_AGENT = 'hitlist dataenrichment - taz-article metadata provider'

TAZBOARD_TAZ_WEB_URL = 'https://taz.de/'

# get rid of ssl-warnings
TAZBOARD_ELASTIC_SHOW_SSL_WARN = False
