variables:
  ROLLOUT_RESOURCE_TYPE: deployment
  AUTO_DEVOPS_DEPLOY_DEBUG: 'true'
  POSTGRES_ENABLED: 'true'
  POSTGRES_VERSION: '10'
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: notasecret
  POSTGRES_DB: 'tazboard'
  AUTO_DEVOPS_POSTGRES_CHANNEL: '2'
  DB_MIGRATE: "python manage.py migrate"

include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml

stages:
  - test
  - prepare
  - build
  - review
  - staging
  - canary
  - deploy
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - production
  - cleanup

frontend:lint:
  stage: test
  image: node:12
  before_script:
    - cd tazboard/frontend/static_src
    - npm install
  script:
    - npm run lint
  cache:
    paths:
      - tazboard/frontend/static_src/node_modules/

frontend:unit:
  stage: test
  image: node:12
  before_script:
    - cd tazboard/frontend/static_src
    - npm install
  script:
    - npm run test:unit
  cache:
    paths:
      - tazboard/frontend/static_src/node_modules/

frontend:e2e:
  image: node:12
  stage: test
  before_script:
    - apt update && apt install chromium firefox-esr
    - cd tazboard/frontend/static_src
    - npm install
  script:
    - npm run test:e2e -- -e firefox,chrome
  cache:
    paths:
      - tazboard/frontend/static_src/node_modules/

app:build:
  image: node:12
  stage: prepare
  before_script:
    - cd tazboard/frontend/static_src
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - tazboard/frontend/templates
      - tazboard/frontend/static/app
