from datetime import datetime

from django.utils.timezone import make_aware


KEY_TIMEFRAME_AGGREGATION = "KEY_TIMEFRAME_AGGREGATION"
KEY_TREND_AGGREGATION = "KEY_TREND_AGGREGATION"
KEY_FINGERPRINT_AGGREGATION = "KEY_FINGERPRINT_AGGREGATION"
KEY_TIMESTAMP_AGGREGATION = "KEY_TIMESTAMP_AGGREGATION"
KEY_REFERRER_AGGREGATION = "KEY_REFERRER_AGGREGATION"
KEY_DEVICES_AGGREGATION = "KEY_DEVICES_AGGREGATION"
KEY_TOPLIST_AGGREGTAION = "KEY_TOPLIST_AGGREGTAION"
KEY_EXTRA_FIELDS_AGGREGATION = "KEY_EXTRA_FIELDS_AGGREGATION"
KEY_RANGES_AGGREGATION = "KEY_RANGES_AGGREGATION"
KEY_REFERRERTAGS_FINGERPRINT_AGGREGATION = "KEY_REFERRERTAGS_FINGERPRINT_AGGREGATION"

INTERVAL_10MINUTES = '10m'


MOCK_FAKE_NOW = make_aware(datetime(year=2020, month=7, day=20))
